/**
 * Media pipeline.
 *
 * Turns the masters in assets-source/ into the files the site actually ships,
 * then writes a manifest containing the real dimensions, byte sizes and a
 * base64 LQIP for each one. The manifest is what the database seed reads, so
 * image metadata in the DB is always measured rather than hand-typed.
 *
 * Two kinds of image asset:
 *   LOSSLESS  the NU / Ceasefire finals — converted to *lossless* WebP, so the
 *             shipped pixels are identical to the master. Serving them
 *             untouched is why next.config.ts turns the image optimiser off.
 *   LOSSY     stills that do not need to be pixel-exact — resized and
 *             re-encoded as JPEG. Empty today; the path is here for the next
 *             batch of Midjourney-grade stills.
 *
 * Nothing is built that the site does not use: public/ is the deploy payload,
 * so every file in it has to be reachable from `scripts/seed.ts`.
 *
 * Video: every film gets the 1080p encode the site actually plays. A film whose
 * master is larger than that encode also gets a losslessly remuxed local
 * archive of the master. See the note above FILMS for which one ships.
 *
 * Run: npm run media          (add --force to rebuild videos that are up to date)
 */
import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";
import ffmpegStatic from "ffmpeg-static";
import sharp from "sharp";

const run = promisify(execFile);

const ROOT = process.cwd();
const IMAGE_DIR = path.join(ROOT, "public/images");
const VIDEO_DIR = path.join(ROOT, "public/videos");
const MANIFEST = path.join(ROOT, "src/content/media-manifest.json");

const FORCE = process.argv.includes("--force");

const FFMPEG = ffmpegStatic;
if (!FFMPEG) throw new Error("ffmpeg-static did not resolve a binary for this platform");

/** Longest edge for the lossy JPEG set. next/image derives smaller sizes from this. */
const MAX_EDGE = 2560;
const JPEG_QUALITY = 86;

/*
 * The master and the playback encode.
 *
 * Every film is built twice, and only one of the two ever leaves this machine:
 *
 *   nu-ceasefire.mp4       the untouched 4K master, losslessly remuxed so it
 *                          streams. ~402 MB. Git-ignored — a local archive,
 *                          regenerated by `npm run media`, never deployed.
 *   nu-ceasefire-1080.mp4  the 1920x1080 encode the site plays. Committed to
 *                          git, because it is what gets deployed.
 *
 * The site has to be publishable for free, and git refuses files at 100 MB, so
 * the shipped encode has to land under ~90 MB. Ceasefire is 3840x2160 at 60 fps
 * from a ~50 Mbit/s master, about the least compressible thing there is, so the
 * usual "visually lossless" CRF numbers do not apply. Measured over the full
 * 67.5s, scaled to 1080p, libx264 preset slow, audio copied:
 *
 *   crf 19 → 123.3 MB   crf 21 → 95.3 MB   crf 21.5 → 89.4 MB   crf 22 → 83.8 MB
 *
 * crf 22 is the setting — the best quality that clears the limit with room to
 * spare. crf 21.5 also fits, but by 0.6 MB, close enough that a machine with a
 * different thread count could push the rebuild over.
 */

/** Playback encode: what the site serves. See the note above. */
const PLAYBACK_HEIGHT = 1080;
const PLAYBACK_CRF = 22;
/** Hard ceiling for anything committed to git. */
const PLAYBACK_MAX_BYTES = 90 * 1024 * 1024;

type ImageSource = {
  /** Output basename, also the manifest name and storage key stem. */
  name: string;
  from: string;
  alt: string;
  caption?: string;
};

/** Converted pixel-for-pixel to lossless WebP — no re-compression, ever. */
const LOSSLESS: ImageSource[] = [
  {
    name: "nu-poster",
    from: "assets-source/NU/finals/Nu-poster.png",
    alt: 'Poster for "Nu & Tib: Ceasefire" — a shaggy blue horned monster and a towering red teddy bear square off in a snowbound city at night, a small girl in a pink coat standing between them, the title set in ice-blue and ember-red lettering above.',
    caption: "Nu & Tib: Ceasefire · poster",
  },
  {
    name: "nu-character-sheet",
    from: "assets-source/NU/finals/nu-character-sheet.png",
    alt: "Character model sheet for Nu: four turnaround views of the blue horned monster, four expression studies labelled happy, angry, sad and neutral, a face detail panel, and the character's colour palette.",
    caption: "Nu · character model sheet",
  },
  {
    name: "tib-character-sheet",
    from: "assets-source/NU/finals/tib-character-sheet.png",
    alt: "Character model sheet for Tib: three-quarter, front, three-quarter and back views of the red teddy bear, four expression studies labelled happy, angry, sad and neutral, and a face detail panel.",
    caption: "Tib · character model sheet",
  },
  {
    name: "nu-first-frame",
    from: "assets-source/NU/finals/nu-first-frame.png",
    alt: "Opening frame of the film: the blue horned monster hugs an enormous snowball on a green ridge between snowy peaks, a tiny figure standing on the grass below and a distant city skyline to the right.",
    caption: "Nu & Tib: Ceasefire · opening frame",
  },
  {
    name: "nu-snow",
    from: "assets-source/NU/finals/snow.png",
    alt: "A young man in a red beanie and pale blue puffer coat crouches in deep snow in a city park, packing a snowball, while other people roll snowballs around him and towers rise behind.",
    caption: "Nu & Tib: Ceasefire · the city, before",
  },
  {
    name: "nu-snowball",
    from: "assets-source/NU/finals/snowball.png",
    alt: "A snowball the size of a building rolls down a green ridge toward a city skyline, throwing up a wave of snow.",
    caption: "Nu & Tib: Ceasefire · the snowball",
  },
  {
    name: "cyclops-poster",
    from: "assets-source/the-unbothered-cyclops/the-unbothered-cyclops-poster.png",
    alt: 'Poster for "The Unbothered Cyclops" — a colossal sand-coloured one-eyed giant stands hunched against a pale blue sky, dozens of tiny helmeted soldiers swarming up its arms and legs while a whole army lines up on the red ground at its feet. The title and the credit "a film by Aiden" are set above in raised stone lettering.',
    caption: "The Unbothered Cyclops · poster",
  },
  {
    name: "cyclops-frame-1",
    from: "assets-source/the-unbothered-cyclops/image1.png",
    alt: "Ranks of clay-figure soldiers in green helmets with red crests and red capes march toward the camera against a flat blue sky, several of them blowing curved horns while the one in front shouts.",
    caption: "The Unbothered Cyclops · the army",
  },
  {
    name: "cyclops-frame-2",
    from: "assets-source/the-unbothered-cyclops/image2.png",
    alt: "The giant's bare sand-coloured foot rests on red ground, filling the frame, with a handful of tiny soldiers climbing over its toes and a vast crowd of them massed on the ground below.",
    caption: "The Unbothered Cyclops · the foot",
  },
  {
    name: "cyclops-frame-3",
    from: "assets-source/the-unbothered-cyclops/image3.png",
    alt: "Seen from behind two crested helmets, a thin line of soldiers walks up the giant's outstretched arm toward its hand, while two dense swarms of troops spread across the red ground beyond.",
    caption: "The Unbothered Cyclops · the climb",
  },
];

/**
 * Stills that do not have to be pixel-exact — resized and re-encoded as JPEG.
 *
 * Empty: the site is down to one project, and every still it shows comes from a
 * finished master in LOSSLESS. Add an entry here and re-run `npm run media` when
 * there is a new still that does not warrant lossless WebP.
 */
const LOSSY: ImageSource[] = [];

type Film = {
  /** Basename for the shipped video. */
  name: string;
  from: string;
  /**
   * Whether to also write `<name>.mp4` — the master, remuxed for streaming, as
   * a local archive. Only worth it when the master is bigger than what ships
   * (a 4K original next to a 1080p encode). When the master is already 1080p,
   * the archive would be a second copy of a file that is already backed up in
   * `assets-source/`, and it would sit in `public/` — the deploy payload.
   */
  archiveMaster: boolean;
};

const FILMS: Film[] = [
  {
    name: "nu-ceasefire",
    from: "assets-source/NU/finals/nu&tib_ceasefire.mp4",
    archiveMaster: true,
  },
  {
    // 1920x1080, 15.07s, 24 fps, ~35 Mbit/s, AAC LC 129 kb/s stereo. The
    // encode is built straight from the master: no archive copy, because the
    // master is already 1080p and 62.7 MB of it would ship on every deploy.
    name: "the-unbothered-cyclops",
    from: "assets-source/the-unbothered-cyclops/the-unbothered-cyclops.mp4",
    archiveMaster: false,
  },
];

export type MediaEntry = {
  name: string;
  url: string;
  storageKey: string;
  width: number;
  height: number;
  bytes: number;
  mimeType: string;
  blurDataUrl: string;
  alt: string;
  caption?: string;
};

async function blurPlaceholder(input: Buffer | string): Promise<string> {
  const buf = await sharp(input)
    .resize(16, 16, { fit: "inside" })
    .jpeg({ quality: 40 })
    .toBuffer();
  return `data:image/jpeg;base64,${buf.toString("base64")}`;
}

function report(name: string, width: number, height: number, bytes: number, note = "") {
  const size =
    bytes >= 1024 * 1024
      ? `${(bytes / 1024 / 1024).toFixed(1)} MB`
      : `${(bytes / 1024).toFixed(0)} KB`;
  console.log(`  ${name.padEnd(22)} ${`${width}x${height}`.padEnd(11)} ${size.padStart(9)} ${note}`);
}

/**
 * Fingerprints an image's decoded pixels — alpha forced on, so a source PNG
 * without an alpha channel and a WebP with one still compare as equal.
 */
async function pixelHash(input: string): Promise<string> {
  const raw = await sharp(input).ensureAlpha().raw().toBuffer();
  return createHash("sha256").update(raw).digest("hex");
}

/**
 * Proves a "lossless" conversion really was lossless. Cheap insurance: a
 * mis-set sharp option would otherwise re-compress a final silently.
 */
async function assertPixelIdentical(src: string, out: string): Promise<void> {
  const [a, b] = await Promise.all([pixelHash(src), pixelHash(out)]);
  if (a !== b) {
    throw new Error(
      `${path.basename(out)} is not pixel-identical to ${path.basename(src)} — ` +
        `the conversion re-compressed it. Check the webp() options.`,
    );
  }
}

/** True when `out` exists and is at least as new as `src`. */
async function isFresh(out: string, src: string): Promise<boolean> {
  if (FORCE || !existsSync(out)) return false;
  const [a, b] = await Promise.all([stat(out), stat(src)]);
  return a.mtimeMs >= b.mtimeMs;
}

async function ffmpeg(args: string[]) {
  // maxBuffer: ffmpeg is quiet at this log level, but 4K encodes run long.
  await run(FFMPEG!, ["-hide_banner", "-loglevel", "error", "-y", ...args], {
    maxBuffer: 32 * 1024 * 1024,
  });
}

/**
 * Builds a film's encodes. No poster frame is cut: each project's page uses a
 * true master as its poster, and an unused multi-megabyte WebP in public/
 * would ship on every deploy for nothing.
 */
async function buildFilm(film: Film): Promise<void> {
  const src = path.join(ROOT, film.from);
  const video = path.join(VIDEO_DIR, `${film.name}.mp4`);
  const playback = path.join(VIDEO_DIR, `${film.name}-1080.mp4`);

  // The master, remuxed for streaming. -c copy means not a single pixel or
  // sample changes; only the moov atom moves to the front of the file.
  // Skipped unless the film asked for an archive — see `archiveMaster`.
  if (film.archiveMaster && !(await isFresh(video, src))) {
    console.log(`  writing ${film.name}.mp4 (remux, no re-encode)…`);
    await ffmpeg(["-i", src, "-map", "0:v:0", "-map", "0:a:0", "-c", "copy", "-movflags", "+faststart", video]);
  }

  // Encode from the archive when there is one — it is pixel-identical to the
  // master — and straight from the master otherwise.
  const encodeFrom = film.archiveMaster ? video : src;

  // The playback encode — the only video file that goes into git and out to
  // the web. Audio is copied rather than re-encoded: the masters are already
  // AAC LC stereo, so a second AAC pass would only lose to itself.
  if (!(await isFresh(playback, encodeFrom))) {
    console.log(`  writing ${film.name}-1080.mp4 (libx264 crf ${PLAYBACK_CRF}, preset slow — slow)…`);
    await ffmpeg([
      "-i", encodeFrom,
      "-map", "0:v:0", "-map", "0:a:0",
      "-vf", `scale=-2:${PLAYBACK_HEIGHT}:flags=lanczos`,
      "-c:v", "libx264",
      "-preset", "slow",
      "-crf", String(PLAYBACK_CRF),
      "-pix_fmt", "yuv420p",
      "-c:a", "copy",
      "-movflags", "+faststart",
      playback,
    ]);
  }

  if (film.archiveMaster) {
    const { size: videoBytes } = await stat(video);
    console.log(
      `  ${path.basename(video).padEnd(30)} ${(videoBytes / 1024 / 1024).toFixed(1).padStart(7)} MB  master — local archive, not shipped`,
    );
  }

  const { size: playbackBytes } = await stat(playback);
  console.log(
    `  ${path.basename(playback).padEnd(30)} ${(playbackBytes / 1024 / 1024).toFixed(1).padStart(7)} MB  1080p — this is what ships`,
  );
  if (playbackBytes > PLAYBACK_MAX_BYTES) {
    throw new Error(
      `${path.basename(playback)} is ${(playbackBytes / 1024 / 1024).toFixed(1)} MB, over the ` +
        `${PLAYBACK_MAX_BYTES / 1024 / 1024} MB limit for a committed file. Raise PLAYBACK_CRF.`,
    );
  }
}

async function main() {
  await mkdir(IMAGE_DIR, { recursive: true });
  await mkdir(VIDEO_DIR, { recursive: true });
  await mkdir(path.dirname(MANIFEST), { recursive: true });

  const entries: MediaEntry[] = [];

  console.log("\nlossless WebP (pixel-identical to the master)");
  for (const src of LOSSLESS) {
    const abs = path.join(ROOT, src.from);
    const outName = `${src.name}.webp`;
    const outPath = path.join(IMAGE_DIR, outName);

    const info = await sharp(abs).webp({ lossless: true, effort: 6 }).toFile(outPath);
    await assertPixelIdentical(abs, outPath);

    entries.push({
      name: src.name,
      url: `/images/${outName}`,
      storageKey: `images/${outName}`,
      width: info.width,
      height: info.height,
      bytes: info.size,
      mimeType: "image/webp",
      blurDataUrl: await blurPlaceholder(abs),
      alt: src.alt,
      caption: src.caption,
    });
    report(src.name, info.width, info.height, info.size, "pixel-identical ✓");
  }

  if (LOSSY.length) console.log("\nJPEG");
  for (const src of LOSSY) {
    const abs = path.join(ROOT, src.from);
    const outName = `${src.name}.jpg`;
    const outPath = path.join(IMAGE_DIR, outName);

    const info = await sharp(abs)
      .resize(MAX_EDGE, MAX_EDGE, { fit: "inside", withoutEnlargement: true })
      .jpeg({ quality: JPEG_QUALITY, mozjpeg: true })
      .toFile(outPath);

    entries.push({
      name: src.name,
      url: `/images/${outName}`,
      storageKey: `images/${outName}`,
      width: info.width,
      height: info.height,
      bytes: info.size,
      mimeType: "image/jpeg",
      blurDataUrl: await blurPlaceholder(abs),
      alt: src.alt,
      caption: src.caption,
    });
    report(src.name, info.width, info.height, info.size);
  }

  console.log("\nvideo");
  for (const film of FILMS) {
    await buildFilm(film);
  }

  await writeFile(MANIFEST, JSON.stringify(entries, null, 2) + "\n", "utf8");
  console.log(`\n  manifest → ${path.relative(ROOT, MANIFEST)} (${entries.length} assets)\n`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
